// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: riot/lol/summoner/v1/summoner.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RiotSummoner struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId     string `protobuf:"bytes,1,opt,name=accountId,proto3" json:"accountId,omitempty"`
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Puuid         string `protobuf:"bytes,3,opt,name=puuid,proto3" json:"puuid,omitempty"`
	Id            string `protobuf:"bytes,4,opt,name=id,proto3" json:"id,omitempty"`
	ProfileIconId int32  `protobuf:"varint,5,opt,name=profileIconId,proto3" json:"profileIconId,omitempty"`
	RevisionDate  int64  `protobuf:"varint,6,opt,name=revisionDate,proto3" json:"revisionDate,omitempty"`
	SummonerLevel int32  `protobuf:"varint,7,opt,name=summonerLevel,proto3" json:"summonerLevel,omitempty"`
}

func (x *RiotSummoner) Reset() {
	*x = RiotSummoner{}
	if protoimpl.UnsafeEnabled {
		mi := &file_riot_lol_summoner_v1_summoner_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RiotSummoner) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiotSummoner) ProtoMessage() {}

func (x *RiotSummoner) ProtoReflect() protoreflect.Message {
	mi := &file_riot_lol_summoner_v1_summoner_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiotSummoner.ProtoReflect.Descriptor instead.
func (*RiotSummoner) Descriptor() ([]byte, []int) {
	return file_riot_lol_summoner_v1_summoner_proto_rawDescGZIP(), []int{0}
}

func (x *RiotSummoner) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *RiotSummoner) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RiotSummoner) GetPuuid() string {
	if x != nil {
		return x.Puuid
	}
	return ""
}

func (x *RiotSummoner) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RiotSummoner) GetProfileIconId() int32 {
	if x != nil {
		return x.ProfileIconId
	}
	return 0
}

func (x *RiotSummoner) GetRevisionDate() int64 {
	if x != nil {
		return x.RevisionDate
	}
	return 0
}

func (x *RiotSummoner) GetSummonerLevel() int32 {
	if x != nil {
		return x.SummonerLevel
	}
	return 0
}

type RiotSummonerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Region    string `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	AccountId string `protobuf:"bytes,2,opt,name=accountId,proto3" json:"accountId,omitempty"`
	Name      string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Puuid     string `protobuf:"bytes,4,opt,name=puuid,proto3" json:"puuid,omitempty"`
	Id        string `protobuf:"bytes,5,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RiotSummonerReq) Reset() {
	*x = RiotSummonerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_riot_lol_summoner_v1_summoner_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RiotSummonerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiotSummonerReq) ProtoMessage() {}

func (x *RiotSummonerReq) ProtoReflect() protoreflect.Message {
	mi := &file_riot_lol_summoner_v1_summoner_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiotSummonerReq.ProtoReflect.Descriptor instead.
func (*RiotSummonerReq) Descriptor() ([]byte, []int) {
	return file_riot_lol_summoner_v1_summoner_proto_rawDescGZIP(), []int{1}
}

func (x *RiotSummonerReq) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *RiotSummonerReq) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *RiotSummonerReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RiotSummonerReq) GetPuuid() string {
	if x != nil {
		return x.Puuid
	}
	return ""
}

func (x *RiotSummonerReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type RiotSummonerAccountReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Region    string `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	AccountId string `protobuf:"bytes,2,opt,name=accountId,proto3" json:"accountId,omitempty"`
}

func (x *RiotSummonerAccountReq) Reset() {
	*x = RiotSummonerAccountReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_riot_lol_summoner_v1_summoner_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RiotSummonerAccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiotSummonerAccountReq) ProtoMessage() {}

func (x *RiotSummonerAccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_riot_lol_summoner_v1_summoner_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiotSummonerAccountReq.ProtoReflect.Descriptor instead.
func (*RiotSummonerAccountReq) Descriptor() ([]byte, []int) {
	return file_riot_lol_summoner_v1_summoner_proto_rawDescGZIP(), []int{2}
}

func (x *RiotSummonerAccountReq) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *RiotSummonerAccountReq) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

type RiotSummonerNameReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Region string `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *RiotSummonerNameReq) Reset() {
	*x = RiotSummonerNameReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_riot_lol_summoner_v1_summoner_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RiotSummonerNameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiotSummonerNameReq) ProtoMessage() {}

func (x *RiotSummonerNameReq) ProtoReflect() protoreflect.Message {
	mi := &file_riot_lol_summoner_v1_summoner_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiotSummonerNameReq.ProtoReflect.Descriptor instead.
func (*RiotSummonerNameReq) Descriptor() ([]byte, []int) {
	return file_riot_lol_summoner_v1_summoner_proto_rawDescGZIP(), []int{3}
}

func (x *RiotSummonerNameReq) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *RiotSummonerNameReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RiotSummonerPuuidReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Region string `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	Puuid  string `protobuf:"bytes,2,opt,name=puuid,proto3" json:"puuid,omitempty"`
}

func (x *RiotSummonerPuuidReq) Reset() {
	*x = RiotSummonerPuuidReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_riot_lol_summoner_v1_summoner_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RiotSummonerPuuidReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiotSummonerPuuidReq) ProtoMessage() {}

func (x *RiotSummonerPuuidReq) ProtoReflect() protoreflect.Message {
	mi := &file_riot_lol_summoner_v1_summoner_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiotSummonerPuuidReq.ProtoReflect.Descriptor instead.
func (*RiotSummonerPuuidReq) Descriptor() ([]byte, []int) {
	return file_riot_lol_summoner_v1_summoner_proto_rawDescGZIP(), []int{4}
}

func (x *RiotSummonerPuuidReq) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *RiotSummonerPuuidReq) GetPuuid() string {
	if x != nil {
		return x.Puuid
	}
	return ""
}

type RiotSummonerIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Region string `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	Id     string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *RiotSummonerIdReq) Reset() {
	*x = RiotSummonerIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_riot_lol_summoner_v1_summoner_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RiotSummonerIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiotSummonerIdReq) ProtoMessage() {}

func (x *RiotSummonerIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_riot_lol_summoner_v1_summoner_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiotSummonerIdReq.ProtoReflect.Descriptor instead.
func (*RiotSummonerIdReq) Descriptor() ([]byte, []int) {
	return file_riot_lol_summoner_v1_summoner_proto_rawDescGZIP(), []int{5}
}

func (x *RiotSummonerIdReq) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *RiotSummonerIdReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_riot_lol_summoner_v1_summoner_proto protoreflect.FileDescriptor

var file_riot_lol_summoner_v1_summoner_proto_rawDesc = []byte{
	0x0a, 0x23, 0x72, 0x69, 0x6f, 0x74, 0x2f, 0x6c, 0x6f, 0x6c, 0x2f, 0x73, 0x75, 0x6d, 0x6d, 0x6f,
	0x6e, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x75, 0x6d, 0x6d, 0x6f, 0x6e, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x14, 0x72, 0x69, 0x6f, 0x74, 0x2e, 0x6c, 0x6f, 0x6c, 0x2e,
	0x73, 0x75, 0x6d, 0x6d, 0x6f, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x22, 0xd6, 0x01, 0x0a, 0x0c,
	0x52, 0x69, 0x6f, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x6f, 0x6e, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x70, 0x75, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70,
	0x75, 0x75, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x70, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x49,
	0x63, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x70, 0x72, 0x6f,
	0x66, 0x69, 0x6c, 0x65, 0x49, 0x63, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0c, 0x72, 0x65,
	0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0c, 0x72, 0x65, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x44, 0x61, 0x74, 0x65, 0x12, 0x24,
	0x0a, 0x0d, 0x73, 0x75, 0x6d, 0x6d, 0x6f, 0x6e, 0x65, 0x72, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x73, 0x75, 0x6d, 0x6d, 0x6f, 0x6e, 0x65, 0x72, 0x4c,
	0x65, 0x76, 0x65, 0x6c, 0x22, 0x81, 0x01, 0x0a, 0x0f, 0x52, 0x69, 0x6f, 0x74, 0x53, 0x75, 0x6d,
	0x6d, 0x6f, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69,
	0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x75, 0x75, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x70, 0x75, 0x75, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x4e, 0x0a, 0x16, 0x52, 0x69, 0x6f, 0x74,
	0x53, 0x75, 0x6d, 0x6d, 0x6f, 0x6e, 0x65, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x1c, 0x0a, 0x09, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x41, 0x0a, 0x13, 0x52, 0x69, 0x6f, 0x74,
	0x53, 0x75, 0x6d, 0x6d, 0x6f, 0x6e, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x44, 0x0a, 0x14, 0x52,
	0x69, 0x6f, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x6f, 0x6e, 0x65, 0x72, 0x50, 0x75, 0x75, 0x69, 0x64,
	0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70,
	0x75, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x75, 0x75, 0x69,
	0x64, 0x22, 0x3b, 0x0a, 0x11, 0x52, 0x69, 0x6f, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x6f, 0x6e, 0x65,
	0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x32, 0xfd,
	0x02, 0x0a, 0x13, 0x52, 0x69, 0x6f, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x6f, 0x6e, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5d, 0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x2c, 0x2e, 0x72, 0x69, 0x6f, 0x74, 0x2e, 0x6c, 0x6f, 0x6c, 0x2e, 0x73, 0x75, 0x6d,
	0x6d, 0x6f, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x69, 0x6f, 0x74, 0x53, 0x75, 0x6d,
	0x6d, 0x6f, 0x6e, 0x65, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a,
	0x22, 0x2e, 0x72, 0x69, 0x6f, 0x74, 0x2e, 0x6c, 0x6f, 0x6c, 0x2e, 0x73, 0x75, 0x6d, 0x6d, 0x6f,
	0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x69, 0x6f, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x6f,
	0x6e, 0x65, 0x72, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x29, 0x2e,
	0x72, 0x69, 0x6f, 0x74, 0x2e, 0x6c, 0x6f, 0x6c, 0x2e, 0x73, 0x75, 0x6d, 0x6d, 0x6f, 0x6e, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x69, 0x6f, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x6f, 0x6e, 0x65,
	0x72, 0x4e, 0x61, 0x6d, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x72, 0x69, 0x6f, 0x74, 0x2e,
	0x6c, 0x6f, 0x6c, 0x2e, 0x73, 0x75, 0x6d, 0x6d, 0x6f, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x69, 0x6f, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x6f, 0x6e, 0x65, 0x72, 0x22, 0x00, 0x12, 0x59,
	0x0a, 0x05, 0x50, 0x75, 0x75, 0x69, 0x64, 0x12, 0x2a, 0x2e, 0x72, 0x69, 0x6f, 0x74, 0x2e, 0x6c,
	0x6f, 0x6c, 0x2e, 0x73, 0x75, 0x6d, 0x6d, 0x6f, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x69, 0x6f, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x6f, 0x6e, 0x65, 0x72, 0x50, 0x75, 0x75, 0x69, 0x64,
	0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x72, 0x69, 0x6f, 0x74, 0x2e, 0x6c, 0x6f, 0x6c, 0x2e, 0x73,
	0x75, 0x6d, 0x6d, 0x6f, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x69, 0x6f, 0x74, 0x53,
	0x75, 0x6d, 0x6d, 0x6f, 0x6e, 0x65, 0x72, 0x22, 0x00, 0x12, 0x53, 0x0a, 0x02, 0x49, 0x64, 0x12,
	0x27, 0x2e, 0x72, 0x69, 0x6f, 0x74, 0x2e, 0x6c, 0x6f, 0x6c, 0x2e, 0x73, 0x75, 0x6d, 0x6d, 0x6f,
	0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x69, 0x6f, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x6f,
	0x6e, 0x65, 0x72, 0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x22, 0x2e, 0x72, 0x69, 0x6f, 0x74, 0x2e,
	0x6c, 0x6f, 0x6c, 0x2e, 0x73, 0x75, 0x6d, 0x6d, 0x6f, 0x6e, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x69, 0x6f, 0x74, 0x53, 0x75, 0x6d, 0x6d, 0x6f, 0x6e, 0x65, 0x72, 0x22, 0x00, 0x42, 0x25,
	0x5a, 0x23, 0x6d, 0x65, 0x65, 0x70, 0x2e, 0x67, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73,
	0x2f, 0x72, 0x69, 0x6f, 0x74, 0x2f, 0x6c, 0x6f, 0x6c, 0x2f, 0x73, 0x75, 0x6d, 0x6d, 0x6f, 0x6e,
	0x65, 0x72, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_riot_lol_summoner_v1_summoner_proto_rawDescOnce sync.Once
	file_riot_lol_summoner_v1_summoner_proto_rawDescData = file_riot_lol_summoner_v1_summoner_proto_rawDesc
)

func file_riot_lol_summoner_v1_summoner_proto_rawDescGZIP() []byte {
	file_riot_lol_summoner_v1_summoner_proto_rawDescOnce.Do(func() {
		file_riot_lol_summoner_v1_summoner_proto_rawDescData = protoimpl.X.CompressGZIP(file_riot_lol_summoner_v1_summoner_proto_rawDescData)
	})
	return file_riot_lol_summoner_v1_summoner_proto_rawDescData
}

var file_riot_lol_summoner_v1_summoner_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_riot_lol_summoner_v1_summoner_proto_goTypes = []interface{}{
	(*RiotSummoner)(nil),           // 0: riot.lol.summoner.v1.RiotSummoner
	(*RiotSummonerReq)(nil),        // 1: riot.lol.summoner.v1.RiotSummonerReq
	(*RiotSummonerAccountReq)(nil), // 2: riot.lol.summoner.v1.RiotSummonerAccountReq
	(*RiotSummonerNameReq)(nil),    // 3: riot.lol.summoner.v1.RiotSummonerNameReq
	(*RiotSummonerPuuidReq)(nil),   // 4: riot.lol.summoner.v1.RiotSummonerPuuidReq
	(*RiotSummonerIdReq)(nil),      // 5: riot.lol.summoner.v1.RiotSummonerIdReq
}
var file_riot_lol_summoner_v1_summoner_proto_depIdxs = []int32{
	2, // 0: riot.lol.summoner.v1.RiotSummonerService.Account:input_type -> riot.lol.summoner.v1.RiotSummonerAccountReq
	3, // 1: riot.lol.summoner.v1.RiotSummonerService.Name:input_type -> riot.lol.summoner.v1.RiotSummonerNameReq
	4, // 2: riot.lol.summoner.v1.RiotSummonerService.Puuid:input_type -> riot.lol.summoner.v1.RiotSummonerPuuidReq
	5, // 3: riot.lol.summoner.v1.RiotSummonerService.Id:input_type -> riot.lol.summoner.v1.RiotSummonerIdReq
	0, // 4: riot.lol.summoner.v1.RiotSummonerService.Account:output_type -> riot.lol.summoner.v1.RiotSummoner
	0, // 5: riot.lol.summoner.v1.RiotSummonerService.Name:output_type -> riot.lol.summoner.v1.RiotSummoner
	0, // 6: riot.lol.summoner.v1.RiotSummonerService.Puuid:output_type -> riot.lol.summoner.v1.RiotSummoner
	0, // 7: riot.lol.summoner.v1.RiotSummonerService.Id:output_type -> riot.lol.summoner.v1.RiotSummoner
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_riot_lol_summoner_v1_summoner_proto_init() }
func file_riot_lol_summoner_v1_summoner_proto_init() {
	if File_riot_lol_summoner_v1_summoner_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_riot_lol_summoner_v1_summoner_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RiotSummoner); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_riot_lol_summoner_v1_summoner_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RiotSummonerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_riot_lol_summoner_v1_summoner_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RiotSummonerAccountReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_riot_lol_summoner_v1_summoner_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RiotSummonerNameReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_riot_lol_summoner_v1_summoner_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RiotSummonerPuuidReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_riot_lol_summoner_v1_summoner_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RiotSummonerIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_riot_lol_summoner_v1_summoner_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_riot_lol_summoner_v1_summoner_proto_goTypes,
		DependencyIndexes: file_riot_lol_summoner_v1_summoner_proto_depIdxs,
		MessageInfos:      file_riot_lol_summoner_v1_summoner_proto_msgTypes,
	}.Build()
	File_riot_lol_summoner_v1_summoner_proto = out.File
	file_riot_lol_summoner_v1_summoner_proto_rawDesc = nil
	file_riot_lol_summoner_v1_summoner_proto_goTypes = nil
	file_riot_lol_summoner_v1_summoner_proto_depIdxs = nil
}
