// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: nexus/lol/match/v1/match.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MatchServiceClient is the client API for MatchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MatchServiceClient interface {
	GetMatchParticipants(ctx context.Context, in *GetMatchReq, opts ...grpc.CallOption) (*MatchParticipantsRes, error)
	GetMatchDetails(ctx context.Context, in *GetMatchReq, opts ...grpc.CallOption) (*MatchDetailsRes, error)
	GetMatches(ctx context.Context, in *GetMatchesReq, opts ...grpc.CallOption) (*MatchesRes, error)
	UpdatePlayerMatches(ctx context.Context, in *UpdatePlayerMatchesReq, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type matchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchServiceClient(cc grpc.ClientConnInterface) MatchServiceClient {
	return &matchServiceClient{cc}
}

func (c *matchServiceClient) GetMatchParticipants(ctx context.Context, in *GetMatchReq, opts ...grpc.CallOption) (*MatchParticipantsRes, error) {
	out := new(MatchParticipantsRes)
	err := c.cc.Invoke(ctx, "/nexus.lol.match.v1.MatchService/GetMatchParticipants", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchServiceClient) GetMatchDetails(ctx context.Context, in *GetMatchReq, opts ...grpc.CallOption) (*MatchDetailsRes, error) {
	out := new(MatchDetailsRes)
	err := c.cc.Invoke(ctx, "/nexus.lol.match.v1.MatchService/GetMatchDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchServiceClient) GetMatches(ctx context.Context, in *GetMatchesReq, opts ...grpc.CallOption) (*MatchesRes, error) {
	out := new(MatchesRes)
	err := c.cc.Invoke(ctx, "/nexus.lol.match.v1.MatchService/GetMatches", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchServiceClient) UpdatePlayerMatches(ctx context.Context, in *UpdatePlayerMatchesReq, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/nexus.lol.match.v1.MatchService/UpdatePlayerMatches", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatchServiceServer is the server API for MatchService service.
// All implementations must embed UnimplementedMatchServiceServer
// for forward compatibility
type MatchServiceServer interface {
	GetMatchParticipants(context.Context, *GetMatchReq) (*MatchParticipantsRes, error)
	GetMatchDetails(context.Context, *GetMatchReq) (*MatchDetailsRes, error)
	GetMatches(context.Context, *GetMatchesReq) (*MatchesRes, error)
	UpdatePlayerMatches(context.Context, *UpdatePlayerMatchesReq) (*emptypb.Empty, error)
	mustEmbedUnimplementedMatchServiceServer()
}

// UnimplementedMatchServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMatchServiceServer struct {
}

func (UnimplementedMatchServiceServer) GetMatchParticipants(context.Context, *GetMatchReq) (*MatchParticipantsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMatchParticipants not implemented")
}
func (UnimplementedMatchServiceServer) GetMatchDetails(context.Context, *GetMatchReq) (*MatchDetailsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMatchDetails not implemented")
}
func (UnimplementedMatchServiceServer) GetMatches(context.Context, *GetMatchesReq) (*MatchesRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMatches not implemented")
}
func (UnimplementedMatchServiceServer) UpdatePlayerMatches(context.Context, *UpdatePlayerMatchesReq) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePlayerMatches not implemented")
}
func (UnimplementedMatchServiceServer) mustEmbedUnimplementedMatchServiceServer() {}

// UnsafeMatchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchServiceServer will
// result in compilation errors.
type UnsafeMatchServiceServer interface {
	mustEmbedUnimplementedMatchServiceServer()
}

func RegisterMatchServiceServer(s grpc.ServiceRegistrar, srv MatchServiceServer) {
	s.RegisterService(&MatchService_ServiceDesc, srv)
}

func _MatchService_GetMatchParticipants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMatchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServiceServer).GetMatchParticipants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nexus.lol.match.v1.MatchService/GetMatchParticipants",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServiceServer).GetMatchParticipants(ctx, req.(*GetMatchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchService_GetMatchDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMatchReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServiceServer).GetMatchDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nexus.lol.match.v1.MatchService/GetMatchDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServiceServer).GetMatchDetails(ctx, req.(*GetMatchReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchService_GetMatches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMatchesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServiceServer).GetMatches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nexus.lol.match.v1.MatchService/GetMatches",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServiceServer).GetMatches(ctx, req.(*GetMatchesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchService_UpdatePlayerMatches_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePlayerMatchesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServiceServer).UpdatePlayerMatches(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/nexus.lol.match.v1.MatchService/UpdatePlayerMatches",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServiceServer).UpdatePlayerMatches(ctx, req.(*UpdatePlayerMatchesReq))
	}
	return interceptor(ctx, in, info, handler)
}

// MatchService_ServiceDesc is the grpc.ServiceDesc for MatchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nexus.lol.match.v1.MatchService",
	HandlerType: (*MatchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetMatchParticipants",
			Handler:    _MatchService_GetMatchParticipants_Handler,
		},
		{
			MethodName: "GetMatchDetails",
			Handler:    _MatchService_GetMatchDetails_Handler,
		},
		{
			MethodName: "GetMatches",
			Handler:    _MatchService_GetMatches_Handler,
		},
		{
			MethodName: "UpdatePlayerMatches",
			Handler:    _MatchService_UpdatePlayerMatches_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "nexus/lol/match/v1/match.proto",
}
