// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: gateway/lol/match/v1/match.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GatewayMatchPlayerReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Region string `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	Puuid  string `protobuf:"bytes,2,opt,name=puuid,proto3" json:"puuid,omitempty"`
}

func (x *GatewayMatchPlayerReq) Reset() {
	*x = GatewayMatchPlayerReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_gateway_lol_match_v1_match_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GatewayMatchPlayerReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayMatchPlayerReq) ProtoMessage() {}

func (x *GatewayMatchPlayerReq) ProtoReflect() protoreflect.Message {
	mi := &file_gateway_lol_match_v1_match_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayMatchPlayerReq.ProtoReflect.Descriptor instead.
func (*GatewayMatchPlayerReq) Descriptor() ([]byte, []int) {
	return file_gateway_lol_match_v1_match_proto_rawDescGZIP(), []int{0}
}

func (x *GatewayMatchPlayerReq) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *GatewayMatchPlayerReq) GetPuuid() string {
	if x != nil {
		return x.Puuid
	}
	return ""
}

var File_gateway_lol_match_v1_match_proto protoreflect.FileDescriptor

var file_gateway_lol_match_v1_match_proto_rawDesc = []byte{
	0x0a, 0x20, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x6c, 0x6f, 0x6c, 0x2f, 0x6d, 0x61,
	0x74, 0x63, 0x68, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x14, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2e, 0x6c, 0x6f, 0x6c, 0x2e,
	0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x76, 0x31, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x45, 0x0a, 0x15, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x12, 0x16,
	0x0a, 0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x75, 0x75, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x75, 0x75, 0x69, 0x64, 0x32, 0x73, 0x0a, 0x13,
	0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x5c, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61,
	0x79, 0x65, 0x72, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x65, 0x73, 0x12, 0x2b, 0x2e, 0x67, 0x61, 0x74,
	0x65, 0x77, 0x61, 0x79, 0x2e, 0x6c, 0x6f, 0x6c, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x76,
	0x31, 0x2e, 0x47, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x50, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22,
	0x00, 0x42, 0x25, 0x5a, 0x23, 0x6d, 0x65, 0x65, 0x70, 0x2e, 0x67, 0x67, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x73, 0x2f, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x6c, 0x6f, 0x6c, 0x2f,
	0x6d, 0x61, 0x74, 0x63, 0x68, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_gateway_lol_match_v1_match_proto_rawDescOnce sync.Once
	file_gateway_lol_match_v1_match_proto_rawDescData = file_gateway_lol_match_v1_match_proto_rawDesc
)

func file_gateway_lol_match_v1_match_proto_rawDescGZIP() []byte {
	file_gateway_lol_match_v1_match_proto_rawDescOnce.Do(func() {
		file_gateway_lol_match_v1_match_proto_rawDescData = protoimpl.X.CompressGZIP(file_gateway_lol_match_v1_match_proto_rawDescData)
	})
	return file_gateway_lol_match_v1_match_proto_rawDescData
}

var file_gateway_lol_match_v1_match_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gateway_lol_match_v1_match_proto_goTypes = []interface{}{
	(*GatewayMatchPlayerReq)(nil), // 0: gateway.lol.match.v1.GatewayMatchPlayerReq
	(*emptypb.Empty)(nil),         // 1: google.protobuf.Empty
}
var file_gateway_lol_match_v1_match_proto_depIdxs = []int32{
	0, // 0: gateway.lol.match.v1.GatewayMatchService.UpdatePlayerMatches:input_type -> gateway.lol.match.v1.GatewayMatchPlayerReq
	1, // 1: gateway.lol.match.v1.GatewayMatchService.UpdatePlayerMatches:output_type -> google.protobuf.Empty
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gateway_lol_match_v1_match_proto_init() }
func file_gateway_lol_match_v1_match_proto_init() {
	if File_gateway_lol_match_v1_match_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_gateway_lol_match_v1_match_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GatewayMatchPlayerReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_gateway_lol_match_v1_match_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_gateway_lol_match_v1_match_proto_goTypes,
		DependencyIndexes: file_gateway_lol_match_v1_match_proto_depIdxs,
		MessageInfos:      file_gateway_lol_match_v1_match_proto_msgTypes,
	}.Build()
	File_gateway_lol_match_v1_match_proto = out.File
	file_gateway_lol_match_v1_match_proto_rawDesc = nil
	file_gateway_lol_match_v1_match_proto_goTypes = nil
	file_gateway_lol_match_v1_match_proto_depIdxs = nil
}
