// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: riot/account/v1/account.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RiotAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Puuid    string `protobuf:"bytes,1,opt,name=puuid,proto3" json:"puuid,omitempty"`
	GameName string `protobuf:"bytes,2,opt,name=gameName,proto3" json:"gameName,omitempty"`
	TagLine  string `protobuf:"bytes,3,opt,name=tagLine,proto3" json:"tagLine,omitempty"`
}

func (x *RiotAccount) Reset() {
	*x = RiotAccount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_riot_account_v1_account_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RiotAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiotAccount) ProtoMessage() {}

func (x *RiotAccount) ProtoReflect() protoreflect.Message {
	mi := &file_riot_account_v1_account_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiotAccount.ProtoReflect.Descriptor instead.
func (*RiotAccount) Descriptor() ([]byte, []int) {
	return file_riot_account_v1_account_proto_rawDescGZIP(), []int{0}
}

func (x *RiotAccount) GetPuuid() string {
	if x != nil {
		return x.Puuid
	}
	return ""
}

func (x *RiotAccount) GetGameName() string {
	if x != nil {
		return x.GameName
	}
	return ""
}

func (x *RiotAccount) GetTagLine() string {
	if x != nil {
		return x.TagLine
	}
	return ""
}

type RiotAccountReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Region   string `protobuf:"bytes,1,opt,name=region,proto3" json:"region,omitempty"`
	Puuid    string `protobuf:"bytes,2,opt,name=puuid,proto3" json:"puuid,omitempty"`
	GameName string `protobuf:"bytes,3,opt,name=gameName,proto3" json:"gameName,omitempty"`
	TagLine  string `protobuf:"bytes,4,opt,name=tagLine,proto3" json:"tagLine,omitempty"`
}

func (x *RiotAccountReq) Reset() {
	*x = RiotAccountReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_riot_account_v1_account_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RiotAccountReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RiotAccountReq) ProtoMessage() {}

func (x *RiotAccountReq) ProtoReflect() protoreflect.Message {
	mi := &file_riot_account_v1_account_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RiotAccountReq.ProtoReflect.Descriptor instead.
func (*RiotAccountReq) Descriptor() ([]byte, []int) {
	return file_riot_account_v1_account_proto_rawDescGZIP(), []int{1}
}

func (x *RiotAccountReq) GetRegion() string {
	if x != nil {
		return x.Region
	}
	return ""
}

func (x *RiotAccountReq) GetPuuid() string {
	if x != nil {
		return x.Puuid
	}
	return ""
}

func (x *RiotAccountReq) GetGameName() string {
	if x != nil {
		return x.GameName
	}
	return ""
}

func (x *RiotAccountReq) GetTagLine() string {
	if x != nil {
		return x.TagLine
	}
	return ""
}

var File_riot_account_v1_account_proto protoreflect.FileDescriptor

var file_riot_account_v1_account_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x72, 0x69, 0x6f, 0x74, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2f, 0x76,
	0x31, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0f, 0x72, 0x69, 0x6f, 0x74, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x76, 0x31,
	0x22, 0x59, 0x0a, 0x0b, 0x52, 0x69, 0x6f, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x70, 0x75, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67, 0x61, 0x6d, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x61, 0x67, 0x4c, 0x69, 0x6e, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x74, 0x61, 0x67, 0x4c, 0x69, 0x6e, 0x65, 0x22, 0x74, 0x0a, 0x0e, 0x52,
	0x69, 0x6f, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a,
	0x06, 0x72, 0x65, 0x67, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72,
	0x65, 0x67, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x75, 0x75, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x75, 0x75, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x67,
	0x61, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x67,
	0x61, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x61, 0x67, 0x4c, 0x69,
	0x6e, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x61, 0x67, 0x4c, 0x69, 0x6e,
	0x65, 0x32, 0xa9, 0x01, 0x0a, 0x12, 0x52, 0x69, 0x6f, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x05, 0x50, 0x75, 0x75, 0x69,
	0x64, 0x12, 0x1f, 0x2e, 0x72, 0x69, 0x6f, 0x74, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x2e, 0x76, 0x31, 0x2e, 0x52, 0x69, 0x6f, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x1a, 0x1c, 0x2e, 0x72, 0x69, 0x6f, 0x74, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x2e, 0x76, 0x31, 0x2e, 0x52, 0x69, 0x6f, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x22, 0x00, 0x12, 0x49, 0x0a, 0x06, 0x52, 0x69, 0x6f, 0x74, 0x49, 0x64, 0x12, 0x1f, 0x2e, 0x72,
	0x69, 0x6f, 0x74, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x69, 0x6f, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x1c, 0x2e,
	0x72, 0x69, 0x6f, 0x74, 0x2e, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x69, 0x6f, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x22, 0x00, 0x42, 0x20, 0x5a,
	0x1e, 0x6d, 0x65, 0x65, 0x70, 0x2e, 0x67, 0x67, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f,
	0x72, 0x69, 0x6f, 0x74, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x2f, 0x76, 0x31, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_riot_account_v1_account_proto_rawDescOnce sync.Once
	file_riot_account_v1_account_proto_rawDescData = file_riot_account_v1_account_proto_rawDesc
)

func file_riot_account_v1_account_proto_rawDescGZIP() []byte {
	file_riot_account_v1_account_proto_rawDescOnce.Do(func() {
		file_riot_account_v1_account_proto_rawDescData = protoimpl.X.CompressGZIP(file_riot_account_v1_account_proto_rawDescData)
	})
	return file_riot_account_v1_account_proto_rawDescData
}

var file_riot_account_v1_account_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_riot_account_v1_account_proto_goTypes = []interface{}{
	(*RiotAccount)(nil),    // 0: riot.account.v1.RiotAccount
	(*RiotAccountReq)(nil), // 1: riot.account.v1.RiotAccountReq
}
var file_riot_account_v1_account_proto_depIdxs = []int32{
	1, // 0: riot.account.v1.RiotAccountService.Puuid:input_type -> riot.account.v1.RiotAccountReq
	1, // 1: riot.account.v1.RiotAccountService.RiotId:input_type -> riot.account.v1.RiotAccountReq
	0, // 2: riot.account.v1.RiotAccountService.Puuid:output_type -> riot.account.v1.RiotAccount
	0, // 3: riot.account.v1.RiotAccountService.RiotId:output_type -> riot.account.v1.RiotAccount
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_riot_account_v1_account_proto_init() }
func file_riot_account_v1_account_proto_init() {
	if File_riot_account_v1_account_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_riot_account_v1_account_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RiotAccount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_riot_account_v1_account_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RiotAccountReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_riot_account_v1_account_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_riot_account_v1_account_proto_goTypes,
		DependencyIndexes: file_riot_account_v1_account_proto_depIdxs,
		MessageInfos:      file_riot_account_v1_account_proto_msgTypes,
	}.Build()
	File_riot_account_v1_account_proto = out.File
	file_riot_account_v1_account_proto_rawDesc = nil
	file_riot_account_v1_account_proto_goTypes = nil
	file_riot_account_v1_account_proto_depIdxs = nil
}
